entity.ikto_environment_indicator.collection:
  path: '/admin/config/development/ikto-environment-indicator/switcher'
  defaults:
    _entity_list: 'ikto_environment_indicator'
    _title: 'Environment Indicator Switcher'
  requirements:
    _permission: 'administer ikto environment indicator settings'

entity.ikto_environment_indicator.delete_form:
  path: '/admin/config/development/ikto-environment-indicator/manage/{ikto_environment_indicator}/delete'
  defaults:
    _entity_form: ikto_environment_indicator.delete
  requirements:
    _entity_access: 'ikto_environment_indicator.delete'

entity.ikto_environment_indicator.edit_form:
  path: '/admin/config/development/ikto-environment-indicator/manage/{ikto_environment_indicator}'
  defaults:
    _entity_form: ikto_environment_indicator.default
  requirements:
    _entity_access: 'ikto_environment_indicator.update'

entity.ikto_environment_indicator.add:
  path: '/admin/config/development/ikto-environment-indicator/switcher/add'
  defaults:
    _entity_form: ikto_environment_indicator.default
  requirements:
    _entity_create_access: 'ikto_environment_indicator'

ikto_environment_indicator.settings:
  path: '/admin/config/development/ikto-environment-indicator'
  defaults:
    _form: '\Drupal\ikto_environment_indicator\Form\EnvironmentIndicatorSettingsForm'
    _title: 'Environment Indicator Settings'
  requirements:
    _permission: 'administer ikto environment indicator settings'
