<?php

require_once __DIR__ . '/ikto_environment_indicator.inc';

use Drupal\Core\Cache\Cache;

/**
 * Implements hook_toolbar().
 */
function ikto_environment_indicator_toolbar() {

  if (!_ikto_environment_indicator_toolbar_intergration_is_enabled()) {
    return array();
  }

  /**
   * @var \Drupal\ikto_environment_indicator\EnvironmentInfoServiceInterface $activeEnvironment
   */
  $activeEnvironment = \Drupal::service('ikto_environment_indicator.active_environment_info');

  $permission = \Drupal::currentUser()
    ->hasPermission('access ikto environment indicator');
  if (!$permission) {
    $permission = \Drupal::currentUser()
      ->hasPermission('access ikto environment indicator ' . $activeEnvironment->getMachineName());
  }

  $items['ikto_environment_indicator'] = [
    // Include the toolbar_tab_wrapper to style the link like a toolbar tab.
    // Exclude the theme wrapper if custom styling is desired.
    '#type' => 'toolbar_item',
    '#access' => $permission,
    '#cache' => [
      'tags'      => $activeEnvironment->getCacheTags(),
      'contexts'  => $activeEnvironment->getCacheContexts(),
      'max-age'   => $activeEnvironment->getCacheMaxAge(),
    ],
    '#weight' => 125,
  ];

  $items['ikto_environment_indicator']['tab'] = [
    '#type' => 'link',
    '#access' => $permission,
    '#title' => $activeEnvironment->getDisplayNameFull(),
    '#url' => \Drupal\Core\Url::fromRoute('ikto_environment_indicator.settings'),
    '#options' => [
      'attributes' => [
        'title' => t('Environment'),
        'class' => [
          'toolbar-icon',
          'toolbar-item',
          'toolbar-icon-environment',
        ],
      ],
    ],
  ];

  $items['ikto_environment_indicator']['#attached'] = [
    'library' => ['ikto_environment_indicator/drupal.ikto_environment_indicator'],
    'drupalSettings' => [
      'iktoEnvironmentIndicator' => [
        'fgColor' => $activeEnvironment->getFgColor(),
        'bgColor' => $activeEnvironment->getBgColor(),
      ],
    ],
  ];

  return $items;
}
