services:
  ikto_environment_indicator.environment_indicator_active:
    class: Drupal\ikto_environment_indicator\EnvironmentIndicatorActive
    arguments: ['@cache.default']
    class:
      - ['init', []]
  ikto_environment_indicator.subscriber.get_environment:
    class: Drupal\ikto_environment_indicator\EventListener\GetEnvironmentSubscriber
    arguments:
      - '@config.factory'
      - '@entity_type.manager'
      - '@ikto_environment_indicator.environment_indicator_active'
    tags:
      - { name: event_subscriber }
  ikto_environment_indicator.git_info:
    class: Drupal\ikto_environment_indicator\GitInfoService
    arguments:
      - '@config.factory'
      - '@cache.default'
