ikto_environment_indicator.settings:
  title: 'Environment Indicator Settings'
  parent: system.admin_config_development
  description: 'Settings to configure the environment indicators.'
  route_name: ikto_environment_indicator.settings
